### ISSUE TITLE
five star rating of pictures

### ISSUE THREAD

**Issue by wein-geist** [nextcloud/photos#425]
**How I do it now**
Assume having a folder containing the pictures of an event/vacation/etc. I usually create a subfolder "best-of" or similar containing a subset with the best pictures. This leads to duplicates of pictures and is kind of a messy way to organize photos.

**Describe the solution you'd like**
I would like to suggest a rating system for Photos. Every user could develop his own rules. Mine would be for example 
- 1*: default
- 3*: best 20 pics
- 4*: best 5 pics
- 5*: absolute masterpiece, maybe 20 pictures in all of my photos. 

In order to do this, following features are needed:
- initially, all pictures are unrated
- bulk rating per album/folder should be possible (eg. set all to ***..)
- Set rating directly when viewing them, therefore the viewer would need to feature a rating element.
- When viewing an album/folder, one should be able to filter e.g. tree stars and above
- Cherry on top: when sharing an album, only share 3 stars or better

**Describe alternatives you've considered**
Folder with a subset copy of the best 20 something pictures.
At the moment there is a star feature in Photos. This doesn't allow for a more defined rating, plus you cant filter albums by starred pictures, only a global view of them.

**Comment by skjnldsv** [comment]
@jancborchardt

**Comment by alexanderdd** [comment]
I think we need a decision if ratings will be implemented or not. How do we make that decision?
If yes, we should open separate reports for individual steps that you named after "following features are needed:"

In your idea, is the rating also saved in the file in metadata?
Is the rating of a foto the same for all users?
 (I think that both would be good)

**Comment by jancborchardt** [comment]
There should be the ability to favorite photos of course, like in Files and other apps of Nextcloud. It should also of course be symmetric to the favoriting in Files, reflecting the status the same in each app.
Currently it’s not very easy to favorite a photo largely because the menu is missing in the viewer: https://github.com/nextcloud/viewer/pull/15

> you cant filter albums by starred pictures, only a global view of them.

That is a very good point @dlauper, and we should fix that by sorting favorites inside a folder up top of that folder so they are directly visible. Just like we do in Files, Notes, Talk and other apps.

-------

On the point of a rating scale: A full rating scale from 1 to 5 is out of scope here and much too complex for the majority of users. We’re not aiming to be Adobe Lightroom. ;)

Also comparing to other related solutions:
- Google Photos has simple on/off favoriting https://www.theverge.com/2018/5/21/17377738/google-photos-favorites-new-feature
- Same for Photos on Mac and iOS https://www.oreilly.com/library/view/photos-for-mac/9781491927328/ch04.html
- Same for Instagram

Hence we go for what people are used to, simple favoriting yes/no.

**Comment by dlauper** [comment]
@alexanderdd I dont know all possibilities of a photos metadata, but if it's possible I'd say yes. If two users dont agree about the rating, well thats why there is a chat function for each file ; )  

@jancborchardt if you're worried about the users, could we leave it to the server admins to decide? One check-mark in the admin settings "use 5 star rating"? Could even be unchecked by default.
I'm no programmer, but in terms of implementation, favorites (in other words 0 or 1 star rating) or a 0 to 5 star rating doesn't seem too different to code, at least for the backend. Of course, UI would need to correctly display both versions.
I know photos does not aim to be Lightroom in terms of photo editing, but in terms of photo organization, why not compete? I've heard people complain about photo organization of Lightroom, because the cloud backup, and therefore remote photo access is not self-hosted. I'm convinced that Nextcloud Photos could fill a gap in this area

**Comment by jancborchardt** [comment]
> if you're worried about the users, could we leave it to the server admins to decide?

No, for several reasons:
- Someone needs to implement and maintain it
- Every setting needs to be tested, so this increases the testing matrix, and our workload
- Inconsistent user experience across different Nextclouds
- Sysadmins are not designers and should not make design decisions

So – we decide on 1 way to do it and go with that. And for now, that is the ability to favorite a photo, which is also consistent with favoriting in Files, Mail, Talk, etc etc., and the other widely used solutions I mentioned above.

Also see [Choosing our Preferences](https://ometer.com/preferences.html) which is linked from our [Nextcloud Design guidelines](https://nextcloud.com/design/) as well.

**Comment by alexanderdd** [comment]
I still don't know how decisions are made around here (I already asked earlier).
Looks like @jancborchardt is in favour of favourites, not ratings. If we go this path, this issue should be closed as "won't be implemented" and a new issue opened "favourite implementation", which has all the points from previous comments (sort at top.etc)

**Comment by skjnldsv** [comment]
> I still don't know how decisions are made around here (I already asked earlier).

Depends on which decision we're talking about.
For UX or UI, @jancborchardt have the final word here.
For technical implementation and features, this is up to engineers (features can also cross multiple departments).
In any case, we usually discuss with people here or in real life and then see the common grounds. Then specify the chosen path on the issue directly :)

**Comment by alexanderdd** [comment]
OK.

So can you @jancborchardt please make a decision if Nextcloud Photos uses favourites and/or ratings? If the answer is favourites only, please close this issue as "won't be implemented" and open a new issue "favourite implementation", which has all the info from previous comments (sort at top.etc).

**Comment by suka97** [comment]
Any news on this one? I'm also interested as for picking the best pictures of holiday trips

**Comment by lumpiluk** [comment]
Looking for a similar feature, I am curious how you would handle ratings by multiple users for the same set of pictures. Would this proposal only support private per-user favorites? For example, I would find it very useful to be able to filter or sort pictures by an aggregate rating or the number of favs.

**Comment by alexanderdd** [comment]
@lumpiluk good point, the standard way of favoriting items in Nextcloud is per-user. With images, you usually want ratings system wide. (let's say a family member does the work to rate all pictures, of course the other family members want to access this rating data. Same in a company that manages lots of photos: the person doing the rating is not the only one who wants access to best-rated photos).

I personally use digikam a lot, it uses IPTC metadata to store rating in the file. This is the professional way, and something probably a lot of people will end up with if they organize photos for a long time (or use other professional photo management software, there are also web apps like photoprism etc) https://docs.digikam.org/en/asset_management/organize_find.html#rating-and-ranking

A workaround for everyone needing this now: You can use digikam for ratings (make sure to set that ratings are stored in the files) and store your files in Nextcloud, then other machines that also run digikam will also see the rating. For mobile, you can use F-Stop gallery which can also access/change these 5-star ratings.

**Comment by susnux** [comment]
> There should be the ability to favorite photos of course, like in Files and other apps of Nextcloud. It should also of course be symmetric to the favoriting in Files, reflecting the status the same in each app.

This will be included in Nextcloud 35

**Comment by alexanderdd** [comment]
@wein-geist @susnux @jancborchardt 

This issue is explicitly about five star rating but AFAIK the linked PR implements the favourite on/off rating. So I reopen. Maybe you want to close this as "wontfix", but IMO it should not be closed as "implemented" (thats what it looked like now).

In https://github.com/nextcloud/photos/issues/425#issuecomment-709969400 Jan says that five star rating is too complex for people. I disagree. People use 5 stars daily and with ease, product reviews, google maps place reviews etc. and also on apps.nextcloud.com

Favourite on/off rating only makes sense for lightweight use. If you use Nextcloud for all your photos and for 20+ years, it is not useful anymore.

IMO the five star rating should be stored in EXIF for interoperability and Nextclouds "if there is a standard we use it" principle.

IMO five star rating could exist in addition to the now implemented favourite on/off.

As mentioned before, there is https://apps.nextcloud.com/apps/starrate which could be an inspiration.

**Comment by susnux** [comment]
> In https://github.com/nextcloud/photos/issues/425#issuecomment-709969400 Jan says that five star rating is too complex for people.

Yes so its for now out of scope for us.
But we can leave this open if there is a huge community demand on this.
